name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when the main branch is updated

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Match your version

      - name: Install dependencies
        run: npm install  # This step uses npm, not yarn

      - name: Build the project
        run: npm run build  # Run the build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Path to the folder containing the built website
